### ISSUE TITLE
[EPIC] Analytics V1

### ISSUE THREAD

**Issue by RAMTO** [LimeChain/HeliSwap-frontend#281]
✍️ [Notion documentation](https://www.notion.so/limechain/Analytics-2f147d6fa62f4a16b63d5a512b94e079)
- [x] LimeChain/HeliSwap-frontend#283
- [x] LimeChain/HeliSwap-frontend#286
- [x] https://github.com/LimeChain/HeliSwap-backend/issues/150
- [x] https://github.com/LimeChain/HeliSwap-backend/issues/215
- [x] LimeChain/HeliSwap-frontend#284
- [x] https://github.com/LimeChain/HeliSwap-backend/issues/151
- [x] LimeChain/HeliSwap-frontend#282
- [x] LimeChain/HeliSwap-frontend#285
- [x] #456
