### ISSUE TITLE
[EPIC] UI Integration

### ISSUE THREAD

**Issue by RAMTO** [LimeChain/HeliSwap-frontend#79]
### General 
- [x] https://github.com/LimeChain/HeliSwap-frontend/issues/80
- [x] https://github.com/LimeChain/HeliSwap-frontend/issues/81

### Components 
- [x] https://github.com/LimeChain/HeliSwap-frontend/issues/82
- [x] https://github.com/LimeChain/HeliSwap-frontend/issues/89
- [x] https://github.com/LimeChain/HeliSwap-frontend/issues/91
- [x] https://github.com/LimeChain/HeliSwap-frontend/issues/103
- [x] https://github.com/LimeChain/HeliSwap-frontend/issues/106
- [x] https://github.com/LimeChain/HeliSwap-frontend/issues/126
